Repository oielay/GTIO_Votacion, pull requests merged in 2025-05, with the labels that each got.

#92 fix (frontend/cd): Arreglado bug frontend y reducido tiempo de despliegue #88
  .github/workflows/ci-cd.yml
  Frontend/astro.config.mjs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/icons/close.svg
  Frontend/public/icons/info.svg
  Frontend/public/icons/navItem1.svg
  Frontend/public/icons/navItem2.svg
  Frontend/public/icons/navItem3.svg
  Frontend/public/icons/navItem4.svg
  Frontend/public/icons/navItemMove.svg
  Frontend/src/components/Header.astro
  Frontend/src/components/Home.astro
  Frontend/src/components/ParticipantBack.jsx
  Frontend/src/components/ParticipantFront.jsx
  Frontend/src/components/Participants.jsx
  Frontend/src/components/Results.jsx
  Frontend/src/components/Voting.jsx
  Frontend/src/pages/index.astro
  Frontend/src/styles/ParticipantBack.css
  Frontend/src/styles/ParticipantFront.css
  Frontend/src/styles/Participants.css
  Frontend/src/styles/Results.css
  Frontend/src/styles/Voting.css
  Frontend/src/utils/charts.ts
  Frontend/src/utils/getDataFromApi.ts
  Frontend/tsconfig.json
  Terraform/main.tf
  Terraform/modules/api/main.tf
  Terraform/modules/frontend/main.tf
  Terraform/modules/infrastructure/main.tf
  package-lock.json
Labels: frontend, cd

#93 test (infracost): Prueba de cambios de costes para PR #91
  Terraform/infracost_test.tf
Labels: costs

#94 feat (ci-cd): Adición de cálculo de costes a ci-cd y configurado con infracost cloud #91
  .github/workflows/ci-cd.yml
Labels: cd, costs

#95 feat (Api Gateway): Implementación de api gateway en Terraform #89
  .github/workflows/ci-cd.yml
  Backend/Servicio_1/Api.Candidatos/Api.Candidatos/04_Controllers/CandidatesController.cs
  Backend/Servicio_1/Api.Candidatos/Api.Candidatos/Program.cs
  Frontend/Dockerfile
  Frontend/src/utils/getDataFromApi.ts
  Terraform/main.tf
  Terraform/modules/api/main.tf
  Terraform/modules/frontend/main.tf
  Terraform/modules/infrastructure/main.tf
  docker-compose.yml
Labels: enhancement, cd

#101 feat (rfp): Desarrollo en tf del api gateway, separación de entornos en ci-cd e implementación de infracost (costes) #100
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  Backend/Servicio_1/Api.Candidatos/Api.Candidatos/04_Controllers/CandidatesController.cs
  Backend/Servicio_1/Api.Candidatos/Api.Candidatos/Program.cs
  Frontend/Dockerfile
  Frontend/astro.config.mjs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/icons/close.svg
  Frontend/public/icons/info.svg
  Frontend/public/icons/navItem1.svg
  Frontend/public/icons/navItem2.svg
  Frontend/public/icons/navItem3.svg
  Frontend/public/icons/navItem4.svg
  Frontend/public/icons/navItemMove.svg
  Frontend/src/components/Header.astro
  Frontend/src/components/Home.astro
  Frontend/src/components/ParticipantBack.jsx
  Frontend/src/components/ParticipantFront.jsx
  Frontend/src/components/Participants.jsx
  Frontend/src/components/Results.jsx
  Frontend/src/components/Voting.jsx
  Frontend/src/pages/index.astro
  Frontend/src/styles/ParticipantBack.css
  Frontend/src/styles/ParticipantFront.css
  Frontend/src/styles/Participants.css
  Frontend/src/styles/Results.css
  Frontend/src/styles/Voting.css
  Frontend/src/utils/charts.ts
  Frontend/src/utils/getDataFromApi.ts
  Frontend/tsconfig.json
  Terraform/main.tf
  Terraform/modules/api/main.tf
  Terraform/modules/frontend/main.tf
  Terraform/modules/infrastructure/main.tf
  docker-compose.yml
  package-lock.json
Labels: enhancement
